version: "3.9"

services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: diaulo-frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: diaulo-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: diaulofood
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: diaulo-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: diaulofood
    volumes:
      - diaulodata:/var/lib/mysql

volumes:
  diaulodata:
